"""Manifest-only release regression: no server, installer, or packager execution."""
from __future__ import annotations

import ast
import hashlib
from pathlib import Path
import re
import shlex
import tempfile
import unittest


ROOT = Path(__file__).parent
NEW_MODULES = {
    "claude_background_reconciliation.py",
    "claude_history_repair.py", "claude_history_provenance.py", "codex_history_repair.py", "public_chat_shares.py",
    "public_chat_transcript.py", "public_chat_share_routes.py",
}
NEW_MIGRATION = "migrations/0019_team_mailbox_state.sql"


def shell_array(source, name):
    match = re.search(rf"(?ms)^{name}=\((.*?)\)", source)
    if match is None:
        raise AssertionError(f"Missing release array {name}")
    return tuple(shlex.split(match[1]))


def manifest_helpers():
    source = ROOT / "scripts" / "package_release.py"
    tree = ast.parse(source.read_text(), filename=str(source))
    constants = {}
    helpers = []
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id in {"FILES", "DIRECTORY_FILES"}:
                    constants[target.id] = ast.literal_eval(node.value)
        elif isinstance(node, ast.FunctionDef) and node.name in {"validate_release_files", "validate_release_directory"}:
            helpers.append(node)
    if set(constants) != {"FILES", "DIRECTORY_FILES"} or len(helpers) != 2:
        raise AssertionError("Incomplete allowlisted release manifest helpers")
    # Compile only read-only validators. Do not import the packaging module,
    # execute main(), create an archive, or invoke any installer subprocess.
    namespace = {"Path": Path, **constants}
    exec(compile(ast.fix_missing_locations(ast.Module(body=helpers, type_ignores=[])), str(source), "exec"), namespace)
    return namespace


class ReleaseFileManifestTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.manifest = manifest_helpers()
        cls.installer = (ROOT / "install.sh").read_text()
        cls.deployer = (ROOT / "deploy.sh").read_text()

    def test_package_and_installer_require_the_same_complete_runtime(self):
        package = self.manifest["FILES"]
        self.assertEqual(shell_array(self.installer, "RELEASE_FILES"), package)
        self.assertEqual(len(package), len(set(package)))
        self.assertTrue(NEW_MODULES <= set(package))
        self.manifest["validate_release_files"](ROOT)

    def test_package_and_installer_require_migration_19_and_exact_hub_members(self):
        package = self.manifest["DIRECTORY_FILES"]["agentsdock_team_hub"]
        self.assertEqual(shell_array(self.installer, "TEAM_HUB_RELEASE_FILES"), package)
        self.assertIn(NEW_MIGRATION, package)
        # Validate a clean release tree, not interpreter caches left by other
        # local tests. The real packager still rejects generated bytecode.
        with tempfile.TemporaryDirectory(prefix="release-hub-manifest-") as temporary:
            staged = Path(temporary) / "agentsdock_team_hub"
            for name in package:
                target = staged / name
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes((ROOT / "agentsdock_team_hub" / name).read_bytes())
            self.manifest["validate_release_directory"](staged)
            (staged / NEW_MIGRATION).unlink()
            with self.assertRaisesRegex(SystemExit, re.escape(NEW_MIGRATION)):
                self.manifest["validate_release_directory"](staged)

    def test_each_new_module_is_required_before_packaging(self):
        with tempfile.TemporaryDirectory(prefix="release-manifest-") as temporary:
            root = Path(temporary)
            for name in self.manifest["FILES"]:
                (root / name).write_text("synthetic release member\n")
            for name in sorted(NEW_MODULES):
                selected = root / name
                selected.unlink()
                with self.subTest(name=name), self.assertRaisesRegex(SystemExit, re.escape(name)):
                    self.manifest["validate_release_files"](root)
                selected.write_text("synthetic release member\n")

    def test_staged_and_direct_deploy_compile_lists_cover_new_modules(self):
        runtime = {name.removeprefix("$SCRIPT_DIR/") for name in shell_array(self.deployer, "RUNTIME_FILES")}
        self.assertTrue(NEW_MODULES <= runtime)
        for name in NEW_MODULES:
            with self.subTest(name=name):
                self.assertIn(f'"$STAGE_DIR/{name}"', self.installer)
                self.assertIn(f"'$REMOTE_SERVER_DIR/{name}'", self.deployer)
                self.assertIn(name.removesuffix(".py"), self.installer.split("PYTHONPATH=\"$STAGE_DIR\"")[-1])

    def test_frozen_hub_manifest_includes_new_migration_and_current_hashes(self):
        tree = ast.parse((ROOT / "test_team_hub_host.py").read_text())
        suite = next(node for node in tree.body if isinstance(node, ast.ClassDef) and node.name == "VendoredTeamHubParityTests")
        expected = next(ast.literal_eval(node.value) for node in ast.walk(suite)
                        if isinstance(node, ast.Assign) and any(isinstance(target, ast.Name) and target.id == "expected" for target in node.targets))
        self.assertIn(NEW_MIGRATION, expected)
        self.assertEqual(set(expected), set(self.manifest["DIRECTORY_FILES"]["agentsdock_team_hub"]))
        for name, digest in expected.items():
            with self.subTest(name=name):
                self.assertEqual(hashlib.sha256((ROOT / "agentsdock_team_hub" / name).read_bytes()).hexdigest(), digest)


if __name__ == "__main__":
    unittest.main()
