"""Exercise real source validation/staging only, never services or dependencies."""
import os
from pathlib import Path
import shlex
import subprocess
import tempfile
import unittest

from scripts import package_release


ROOT = Path(__file__).resolve().parents[1]


class InstallerSourceCacheTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory(prefix="installer-source-cache-")
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        self.source = self.root / "source"
        self.stage = self.root / "stage"
        self.source.mkdir()
        self.stage.mkdir()
        for name in package_release.FILES:
            (self.source / name).write_text("synthetic release file\n")
        self.hub = self.source / "agentsdock_team_hub"
        for name in package_release.DIRECTORY_FILES["agentsdock_team_hub"]:
            path = self.hub / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text("synthetic module file\n")
        installer = (ROOT / "install.sh").read_text()
        start = installer.index("RELEASE_FILES=(")
        end = installer.index("\ncurrent_release_binding()", start)
        validation = installer[start:end]
        copy_start = installer.index('for name in "${RELEASE_FILES[@]}"; do', end)
        copy_end = installer.index('echo "[2/7]', copy_start)
        self.script = (
            "set -euo pipefail\n"
            f"SOURCE_DIR={shlex.quote(str(self.source))}\n"
            f"STAGE_DIR={shlex.quote(str(self.stage))}\n"
            + validation + installer[copy_start:copy_end]
        )

    def run_stage(self):
        return subprocess.run(["/bin/bash", "-c", self.script], capture_output=True, text=True, timeout=10)

    def test_cache_files_are_ignored_without_modifying_source_or_shipping_them(self):
        for name in ("__pycache__/auth.cpython-313.pyc", "migrations/__pycache__/__init__.cpython-313.pyc", "auth.pyc", "store.pyo"):
            path = self.hub / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(b"synthetic generated bytecode")
        before = {str(path.relative_to(self.source)): path.read_bytes() for path in self.source.rglob("*") if path.is_file()}
        result = self.run_stage()
        self.assertEqual(result.returncode, 0, result.stderr)
        staged = {path.relative_to(self.stage / "agentsdock_team_hub").as_posix() for path in (self.stage / "agentsdock_team_hub").rglob("*") if path.is_file()}
        self.assertEqual(staged, set(package_release.DIRECTORY_FILES["agentsdock_team_hub"]))
        self.assertFalse(list(self.stage.rglob("__pycache__")))
        self.assertEqual(before, {str(path.relative_to(self.source)): path.read_bytes() for path in self.source.rglob("*") if path.is_file()})

    def test_links_in_cache_are_still_rejected(self):
        cache = self.hub / "__pycache__"
        cache.mkdir()
        (cache / "hidden.pyc").symlink_to(self.source / "agent_server.py")
        result = self.run_stage()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("linked or special entries", result.stderr)
        self.assertEqual(list(self.stage.iterdir()), [])

    def test_linked_cache_directory_is_still_rejected(self):
        (self.hub / "__pycache__").symlink_to(self.stage, target_is_directory=True)
        result = self.run_stage()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("linked or special entries", result.stderr)

    def test_special_file_in_cache_is_still_rejected_without_opening_it(self):
        cache = self.hub / "__pycache__"
        cache.mkdir()
        os.mkfifo(cache / "hidden.pyc")
        result = self.run_stage()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("linked or special entries", result.stderr)

    def test_unexpected_regular_files_are_still_rejected(self):
        (self.hub / "local-secret.txt").write_text("must not ship")
        result = self.run_stage()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("unexpected release files", result.stderr)
        self.assertEqual(list(self.stage.iterdir()), [])

    def test_unexpected_directories_are_still_rejected(self):
        (self.hub / "unlisted-directory").mkdir()
        result = self.run_stage()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("unexpected release directories", result.stderr)

    def test_bytecode_does_not_substitute_for_missing_required_source(self):
        (self.hub / "auth.py").unlink()
        (self.hub / "auth.pyc").write_bytes(b"bytecode is not source")
        result = self.run_stage()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("agentsdock_team_hub/auth.py is missing", result.stderr)
        self.assertEqual(list(self.stage.iterdir()), [])


if __name__ == "__main__":
    unittest.main()
